import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import SessionProvider from "@/provider/SessionProvider";
import { Toaster } from "@/components/ui/sonner";

// Import Manrope font
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <AppProvider>
          <SessionProvider>
          {children}
              <Toaster position="top-right" />
          </SessionProvider>
        </AppProvider>
      </body>
    </html>
  );
}
